// Central registry of every collectible category reachable from the Catalog Hub.
// `status: 'active'` categories are wired to a real backend search (see src/routes/catalog*.js).
// `name` values are brand/product names (not translated across locales); `taglineKey`
// points into the `catalog_games` i18n namespace — CatalogHub.jsx resolves it via t().
export const CATALOG_GAMES = [
  {
    slug: 'lego',
    name: 'LEGO',
    emoji: '🧱',
    accent: 'blue',
    status: 'active',
    taglineKey: 'catalog_games.lego',
  },
  {
    slug: 'magic',
    name: 'Magic: The Gathering',
    emoji: '🔮',
    accent: 'purple',
    status: 'active',
    taglineKey: 'catalog_games.magic',
    apiBase: '/api/catalog/magic',
    source: 'Scryfall',
    detailFields: [
      { key: 'type_line', label: 'Tipo' },
      { key: 'mana_cost', label: 'Costo di Mana' },
      { key: 'cmc', label: 'Valore Manaico' },
      { key: 'priceEur', label: 'Prezzo di Mercato', prefix: '€' },
      { key: 'oracle_text', label: 'Testo Carta', full: true },
    ],
  },
  {
    slug: 'yugioh',
    name: 'Yu-Gi-Oh!',
    emoji: '🎴',
    accent: 'amber',
    status: 'active',
    taglineKey: 'catalog_games.yugioh',
    apiBase: '/api/catalog/yugioh',
    source: 'YGOPRODeck',
    detailFields: [
      { key: 'type', label: 'Tipo Carta' },
      { key: 'race', label: 'Razza / Categoria' },
      { key: 'attribute', label: 'Attributo' },
      { key: 'level', label: 'Livello / Rank' },
      { key: 'atk', label: 'ATK' },
      { key: 'def', label: 'DEF' },
      { key: 'desc', label: 'Effetto Carta', full: true },
    ],
  },
  {
    slug: 'lorcana',
    name: 'Disney Lorcana',
    emoji: '✨',
    accent: 'purple',
    status: 'active',
    taglineKey: 'catalog_games.lorcana',
    apiBase: '/api/catalog/lorcana',
    source: 'lorcana-api.com',
    detailFields: [
      { key: 'type', label: 'Tipo' },
      { key: 'color', label: 'Colore Inchiostro' },
      { key: 'cost', label: 'Costo' },
      { key: 'strength', label: 'Forza' },
      { key: 'willpower', label: 'Volontà' },
      { key: 'lore', label: 'Lore' },
      { key: 'body_text', label: 'Testo Carta', full: true },
      { key: 'flavor_text', label: 'Flavor Text', full: true },
    ],
  },
  {
    slug: 'pokemon',
    name: 'Pokémon',
    emoji: '⚡',
    accent: 'emerald',
    status: 'active',
    taglineKey: 'catalog_games.pokemon',
    apiBase: '/api/catalog/pokemon',
    source: 'Pokémon TCG API',
    detailFields: [
      { key: 'supertype', label: 'Supertipo' },
      { key: 'types', label: 'Tipo' },
      { key: 'hp', label: 'PS' },
      { key: 'priceEur', label: 'Prezzo di Mercato', prefix: '€' },
    ],
  },
  {
    slug: 'onepiece',
    name: 'One Piece Card Game',
    emoji: '🏴‍☠️',
    accent: 'rose',
    status: 'active',
    taglineKey: 'catalog_games.onepiece',
    apiBase: '/api/catalog/onepiece',
    source: 'OPTCG API',
    detailFields: [
      { key: 'type', label: 'Tipo Carta' },
      { key: 'color', label: 'Colore' },
      { key: 'cost', label: 'Costo' },
      { key: 'power', label: 'Potenza' },
      { key: 'life', label: 'Vita' },
      { key: 'attribute', label: 'Attributo' },
      { key: 'sub_types', label: 'Sottotipi' },
      { key: 'card_text', label: 'Testo Carta', full: true },
    ],
  },
  {
    slug: 'dragonball',
    name: 'Dragon Ball Super Card Game',
    emoji: '🐉',
    accent: 'amber',
    status: 'active',
    taglineKey: 'catalog_games.dragonball',
    apiBase: '/api/catalog/dragonball',
    source: 'API TCG',
    detailFields: [
      { key: 'color', label: 'Colore' },
      { key: 'power', label: 'Potenza' },
      { key: 'card_number', label: 'Numero Carta' },
      { key: 'priceEur', label: 'Prezzo di Mercato', prefix: '€' },
    ],
  },
  {
    slug: 'funko',
    name: 'Funko Pop!',
    emoji: '🧸',
    accent: 'rose',
    status: 'active',
    taglineKey: 'catalog_games.funko',
    apiBase: '/api/catalog/funko',
    source: 'Open Funko Dataset',
    detailFields: [
      { key: 'series', label: 'Serie' },
    ],
  },
];

export const getCatalogGame = (slug) => CATALOG_GAMES.find((g) => g.slug === slug) || null;
