export const MOCK_LISTINGS = [
  { id: 'mock1', title: 'UCS Millennium Falcon', set_number: '75192', theme: 'Star Wars', price: 650.00, condition: 'Nuovo', box_condition: 'Originale (Sigillata)', instructions: 'Presenti', seller: { username: 'BrickMasterStore', is_pro: true, country: 'it', rating: '100% Positivo', stars: 5 }, description: 'Condizioni perfette, scatola mai aperta MISB.', image_url: 'https://picsum.photos/seed/falcon/800/600', gallery: ['https://picsum.photos/seed/falcon/800/600', 'https://picsum.photos/seed/falcon2/800/600', 'https://picsum.photos/seed/falcon3/800/600'] },
  { id: 'mock2', title: 'Porsche 911 GT3 RS', set_number: '42056', theme: 'Technic', price: 420.00, condition: 'Usato', box_condition: 'Originale (Aperta)', instructions: 'Presenti', seller: { username: 'LegoNerd99', is_pro: false, country: 'de', rating: '98% Positivo', stars: 4 }, description: 'Montato una sola volta e tenuto in vetrina senza luce solare. Tutti i pezzi presenti verificati con Bricklink.', image_url: 'https://picsum.photos/seed/porsche/800/600', gallery: ['https://picsum.photos/seed/porsche/800/600', 'https://picsum.photos/seed/porsche2/800/600'] },
  { id: 'mock3', title: 'Hogwarts Castle', set_number: '71043', theme: 'Harry Potter', price: 380.00, condition: 'Nuovo', box_condition: 'Originale (Sigillata)', instructions: 'Presenti', seller: { username: 'MagicBricks', is_pro: true, country: 'gb', rating: '99% Positivo', stars: 5 }, description: 'Set gigantesco introvabile, scatola in ottime condizioni 9/10.', image_url: 'https://picsum.photos/seed/hogwarts/800/600', gallery: ['https://picsum.photos/seed/hogwarts/800/600'] },
  { id: 'mock4', title: 'Ninjago City Gardens', set_number: '71741', theme: 'Ninjago', price: 290.00, condition: 'Nuovo', box_condition: 'Originale (Danneggiata)', instructions: 'Presenti', seller: { username: 'NinjaBuilds', is_pro: true, country: 'it', rating: '100% Positivo', stars: 5 }, description: 'I sigilli sono integri ma la scatola ha preso un colpo su un angolo durante la spedizione. Ottimo per chi lo vuole montare.', image_url: 'https://picsum.photos/seed/ninjago/800/600', gallery: ['https://picsum.photos/seed/ninjago/800/600', 'https://picsum.photos/seed/ninjago_dmg/800/600'] },
  { id: 'mock5', title: 'Concorde', set_number: '10318', theme: 'Icons', price: 185.00, condition: 'Usato', box_condition: 'Assente', instructions: 'Assenti (Solo PDF)', seller: { username: 'PlaneFan', is_pro: false, country: 'fr', rating: '100% Positivo', stars: 5 }, description: 'Modello fantastico della linea Icons. Spedisco smontato diviso nei colori originali.', image_url: 'https://picsum.photos/seed/concorde/800/600', gallery: ['https://picsum.photos/seed/concorde/800/600'] },
  { id: 'mock6', title: 'Rivendell', set_number: '10316', theme: 'Icons', price: 440.00, condition: 'Nuovo', box_condition: 'Originale (Sigillata)', instructions: 'Presenti', seller: { username: 'MiddleEarthBricks', is_pro: true, country: 'es', rating: '97% Positivo', stars: 4 }, description: 'Splendida replica di Gran Burrone, set intonso e sigillato in scatola marrone originale.', image_url: 'https://picsum.photos/seed/rivendell/800/600', gallery: ['https://picsum.photos/seed/rivendell/800/600', 'https://picsum.photos/seed/rivendell2/800/600', 'https://picsum.photos/seed/rivendell3/800/600'] },
  { id: 'mock7', title: 'Ghostbusters ECTO-1', set_number: '10274', theme: 'Icons', price: 195.00, condition: 'Usato', box_condition: 'Originale (Aperta)', instructions: 'Presenti', seller: { username: 'BusterBricks', is_pro: false, country: 'it', rating: 'Nuovo Utente', stars: 0 }, description: 'Montata un paio d\'anni fa per Halloween. Completa di ruggine finta.', image_url: 'https://picsum.photos/seed/ecto1/800/600', gallery: ['https://picsum.photos/seed/ecto1/800/600'] },
  { id: 'mock8', title: 'Daily Bugle', set_number: '76178', theme: 'Marvel', price: 310.00, condition: 'Nuovo', box_condition: 'Originale (Sigillata)', instructions: 'Presenti', seller: { username: 'SpiderStore', is_pro: true, country: 'us', rating: '100% Positivo', stars: 5 }, description: 'Il set più alto della linea! Introvabile sigillato in Europa.', image_url: 'https://picsum.photos/seed/dailybugle/800/600', gallery: ['https://picsum.photos/seed/dailybugle/800/600', 'https://picsum.photos/seed/dailybugle2/800/600'] },
];
